trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

resources:
  repositories:
  - repository: templates
    name: Pipelines
    type: git
    ref: refs/heads/master

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: true

- template: pipeline-templates/check-text-files.yml@templates

- template: pipeline-templates/gitversion-task.yml@templates
  parameters:
    gitVersionVersion: $(gitVersionVersion)

- script: 'git push https://$(GitHubToken)@github.com/templafy/CustomContentConnector.git'
  displayName: Push to GitHub

- task: AzureContainerApps@1
  displayName: 'Deploy to Azure Container Apps'
  inputs:
    appSourcePath: '$(Build.SourcesDirectory)'
    azureSubscription: 'Templafy Local ResourceGroup Automated'
    acrName: 'customcontentconnectorapicontainerregistry'
    containerAppName: 'custom-content-connector-api'
    imageToBuild: 'customcontentconnectorapicontainerregistry.azurecr.io/custom-content-connector-api'
    resourceGroup: 'Local'
