trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: ConnectorLibraries
- group: PipelineSoftwareVersions

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: true

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: $(gitVersionVersion)
    includePrerelease: true

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'git-version.yml'

- script: 'git push https://$(GitHubToken)@github.com/templafy/CustomContentConnector.git'
  displayName: Push to GitHub

- task: AzureContainerApps@1
  displayName: 'Deploy to Azure Container Apps'
  inputs:
    appSourcePath: '$(Build.SourcesDirectory)'
    azureSubscription: 'Templafy Local ResourceGroup Automated'
    acrName: 'customcontentconnectorapicontainerregistry'
    containerAppName: 'custom-content-connector-api'
    resourceGroup: 'Local'
